version: 0.2

env:
  variables:
    AWS_ACCESS_KEY_ID: ${secretsmanager:aws-secrets-ha-JcPq8E:AWS_ACCESS_KEY}
    AWS_SECRET_ACCESS_KEY: ${secretsmanager:aws-secrets-ha-JcPq8E:AWS_SECRET_KEY}
    AWS_DEFAULT_REGION: "eu-central-1"
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - apt-get update && apt-get install -y unzip
      - curl -fsSL https://releases.hashicorp.com/terraform/0.15.0/terraform_0.15.0_linux_amd64.zip -o terraform.zip
      - unzip terraform.zip -d /usr/local/bin/

  build:
    commands:
      - echo "Executing Terraform init and apply"
      - cd iac  # Navigate into the 'iac' folder
      - terraform init -backend-config=bucket="financial-h-iac-tfstate"
      - terraform apply -auto-approve

artifacts:
  files: '**/*'
